on: [push, pull_request]
name: build
jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      VERSION: '0.1.${GITHUB_RUN_NUMBER}'
      VERSION_FULL: '${VERSION}+${GITHUB_SHA}'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.3'
      - name: Build
        run: |
          GOOS=windows GOARCH=amd64 go build -ldflags "-X main.buildVersion=${VERSION_FULL}" -o ../bin/win-x64/markdown2medium.exe
          GOOS=linux GOARCH=amd64 go build -ldflags "-X main.buildVersion=${VERSION_FULL}" -o ../bin/linux-x64/markdown2medium
        working-directory: ./src
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body: |
            **New**:
            - TODO
            **Fixed**:
            - TODO
            **Changed**:
            - TODO
            **Retired**:
            - TODO
          draft: true
          prerelease: true
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/win-x64/markdown2medium.exe
          asset_name: markdown2medium-${{ env.VERSION }}-win-x64.exe
          asset_content_type: application/vnd.microsoft.portable-executable
      - name: Upload Release Asset
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/linux-x64/markdown2medium.exe
          asset_name: markdown2medium-${{ env.VERSION }}-linux-x64
          asset_content_type: application/octet-stream
